<h3>this iss template for account customer jhgyu</h3>
<div class="owl-carousel" data-mage-init='{"carousel":{"option": value}}'>
    <div class="item">
        <img src="<?php echo $this->getViewFileUrl('images/blog/01_homepage_13.jpg'); ?>">
    </div>
    <div class="item">
        <img src="<?php echo $this->getViewFileUrl('images/blog/01_homepage_14.jpg'); ?>">
    </div>
    <div class="item">
        <img src="<?php echo $this->getViewFileUrl('images/blog/01_homepage_15.jpg'); ?>">
    </div>
</div>
